openapi: 3.0.0
info:
  title: twinder
  description: CS6650 assignment API
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/IGORTON/Twinder/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: swipe
  description: when users sees a profile
- name: matches
  description: who is a user matched with
- name: stats
  description: info about user activity
paths:
  /swipe/{leftorright}/:
    post:
      tags:
      - swipe
      description: Swipe left or right
      operationId: Swipe
      parameters:
      - name: leftorright
        in: path
        description: Ilike or dislike user
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: left
      requestBody:
        description: response details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/swipeDetails'
        required: true
      responses:
        "201":
          description: Write successful
        "400":
          description: Invalid inputs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseMsg'
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseMsg'
components:
  schemas:
    responseMsg:
      type: object
      properties:
        message:
          type: string
    swipeDetails:
      type: object
      properties:
        swiper:
          type: string
          example: "233"
        swipee:
          type: string
          example: "21345"
        comment:
          type: string
          example: "you are not my type, loser"
