/*
 * twinder
 *
 * CS6650 assignment API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResponseMsg struct {
	Message string `json:"message,omitempty"`
}
