/*
 * twinder
 *
 * CS6650 assignment API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SwipeDetails struct {
	Swiper string `json:"swiper,omitempty"`
	Swipee string `json:"swipee,omitempty"`
	Comment string `json:"comment,omitempty"`
}
